"""short link table

Revision ID: 26f36230fab4
Revises: 30666042f2a4
Create Date: 2025-03-26 11:42:10.191590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f36230fab4'
down_revision = '30666042f2a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('short_url', sa.String(length=800), nullable=False),
    sa.Column('last_usage_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_link_id'), 'short_link', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_link_id'), table_name='short_link')
    op.drop_table('short_link')
    # ### end Alembic commands ###
