"""creation date

Revision ID: 98bf3bccefd9
Revises: d470c2ebd2da
Create Date: 2025-03-26 14:48:18.242761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bf3bccefd9'
down_revision = 'd470c2ebd2da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_link', sa.Column('custom_alias', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_link', 'custom_alias')
    # ### end Alembic commands ###
