"""add expire and user

Revision ID: 9e623c258686
Revises: 26f36230fab4
Create Date: 2025-03-26 14:23:34.431305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e623c258686'
down_revision = '26f36230fab4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_link', sa.Column('expires_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('short_link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'short_link', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_link', type_='foreignkey')
    op.drop_column('short_link', 'user_id')
    op.drop_column('short_link', 'expires_at')
    # ### end Alembic commands ###
